services:
  database:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db

  redis:
    image: eqalpha/keydb
    restart: always

  minio:
    image: minio/minio
    command: server /data
    env_file: .env
    volumes:
      - ./data/minio:/data
    restart: always

  caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config

  api:
    image: ghcr.io/revoltchat/server:latest
    env_file: .env
    depends_on:
      - database
      - redis
      - caddy
    restart: always

  events:
    image: ghcr.io/revoltchat/bonfire:latest
    env_file: .env
    depends_on:
      - database
      - redis
      - caddy
    restart: always

  web:
    image: ghcr.io/revoltchat/client:master
    env_file: .env
    depends_on:
      - caddy
    restart: always

  autumn:
    image: ghcr.io/revoltchat/autumn:latest
    env_file: .env
    depends_on:
      - database
      - createbuckets
      - caddy
    environment:
      - AUTUMN_MONGO_URI=mongodb://database
    restart: always

  january:
    image: ghcr.io/revoltchat/january:0.3.4
    depends_on:
      - caddy
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      while ! /usr/bin/mc ready minio; do echo 'Waiting minio...' && sleep 1; done;
      /usr/bin/mc mb minio/attachments;
      /usr/bin/mc mb minio/avatars;
      /usr/bin/mc mb minio/backgrounds;
      /usr/bin/mc mb minio/icons;
      /usr/bin/mc mb minio/banners;
      /usr/bin/mc mb minio/emojis;
      exit 0;
      "
